services:
  - type: web
    name: mytickertracker
    staticSite: true
    buildCommand: npm ci && npm run build
    publishPath: dist
    envVars:
      - key: VITE_FINNHUB_API_KEY
      - key: VITE_SMS_API_URL
