services:
  - type: static
    name: mytickertracker
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_FINNHUB_API_KEY
      - key: VITE_SMS_API_URL
