staticSites:
  - name: mytickertracker
    rootDir: .
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_FINNHUB_API_KEY
        sync: false
      - key: VITE_SMS_API_URL
        sync: false
